### ISSUE TITLE
HTML styles don't render if not using port 80 or 443

### ISSUE THREAD

**Issue by gllona** [AstraBert/llama-4-researcher#9]
Hello! I was able to set up Llama Researcher with `docker compose` behind a `nginx` container to provide SSL connections.

If I run the project with `nginx` listening to port 443, the UI renders fine.

However, if I run the project with `nginx` listening to port 8443 (which is what I need because I run other service in port 443), then the UI don't render the styles. However, the API works fine.

![Image](https://github.com/user-attachments/assets/9dfae5b0-140d-47a0-b29d-a7e3affbfd04)

In the image above, you can that the file `theme.css` is tried to be loaded from port 443, not 8443. I think this is the root cause. There are no other components tried to be loaded from port 443.

I attach below my setup for both port 8443 and port 443. `nginx` runs as a native service in the Ubuntu 24.04 AWS EC2 instance.

Thanks!

#### `./compose.yaml`

```
name: llama-4-researcher

services:
  llama_redis:
    image: redis
    container_name: llama-4-research-redis
    ports:
      - 6379:6379
    restart: always
  llama_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llama-4-research-app
    secrets:
      - groq_key
      - internal_key
      - linkup_key
      - supabase_api_key
      - supabase_api_url
      - postgres_host
      - postgres_user
      - postgres_db
      - postgres_password
    ports:
      - 8000:80
    depends_on:
      - llama_redis
    restart: always
  llama_register:
    build:
      context: .
      dockerfile: Dockerfile.register
    container_name: llama-4-research-register
    secrets:
      - supabase_api_key
      - supabase_api_url
    ports:
      - 7860:80
    depends_on:
      - llama_redis
    restart: always
  nginx:
    image: nginx:1.27.0-alpine
    container_name: llama-4-research-NGINX
    ports:
      - 8080:80
      - 8443:443
    depends_on:
      - llama_app
      - llama_register
    restart: always
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/chat.tools.agileimpacts.com:/etc/letsencrypt/live/chat.tools.agileimpacts.com
      - /etc/letsencrypt/archive/chat.tools.agileimpacts.com:/etc/letsencrypt/archive/chat.tools.agileimpacts.com
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/nginx/ssl/dhparam:/etc/nginx/ssl/dhparam

networks:
  default:
    driver: bridge

secrets:
  groq_key:
    environment: groq_api_key
  linkup_key:
    environment: linkup_api_key
  internal_key:
    environment: internal_api_key
  supabase_api_key:
    environment: supa_key
  supabase_api_url:
    environment: supa_url
  postgres_host:
    environment: pgql_host
  postgres_user:
    environment: pgql_user
  postgres_password:
    environment: pgql_psw
  postgres_db:
    environment: pgql_db

volumes:
  pgdata:
```

#### `./deploy/nginx.conf`

```
# Secure default configuration generated by Mozilla SSL Configuration Generator
# generated 2024-01-21, Mozilla Guideline v5.7, nginx 1.24.0, OpenSSL 3.1.4, intermediate configuration
# https://ssl-config.mozilla.org/#server=nginx&version=1.24.0&config=intermediate&openssl=3.1.4&guideline=5.7

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # To Configure SSL, comment all lines within the Non-SSL section and uncomment all lines under the SSL section. 
    ########################################  Non-SSL  ########################################
    # server_name localhost;
    server_name chat.tools.agileimpacts.com;

    # https://docs.nginx.com/nginx/admin-guide/web-server/compression/
    # gzip on;
    # gzip_vary on;
    # gzip_proxied any;
    # gzip_comp_level 6;
    # gzip_buffers 16 8k;
    # gzip_http_version 1.1;
    # gzip_types text/css application/javascript application/json application/octet-stream;

    # Increase the client_max_body_size to allow larger file uploads
    # The default limits for image uploads as of 11/22/23 is 20MB/file, and 25MB/request
    client_max_body_size 25M;

    #location / {
    #    proxy_pass http://llama_app:80/;
    #}

    ########################################  SSL  ########################################
    # Redirect all http traffic to https
    location / {
        return 301 https://$host:8443$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # https://docs.nginx.com/nginx/admin-guide/web-server/compression/
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/css application/javascript application/json application/octet-stream;

#    ssl_certificate /etc/nginx/ssl/nginx.crt;
#    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_certificate /etc/letsencrypt/live/chat.tools.agileimpacts.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chat.tools.agileimpacts.com/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /etc/nginx/ssl/dhparam
    ssl_dhparam /etc/nginx/ssl/dhparam;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/letsencrypt/live/chat.tools.agileimpacts.com/chain.pem;

    # replace with the IP address of your resolver
    resolver 8.8.8.8 8.8.4.4 valid=300s;

    server_name chat.tools.agileimpacts.com;

    # Increase the client_max_body_size to allow larger file uploads
    # The default limits for image uploads as of 11/22/23 is 20MB/file, and 25MB/request
    client_max_body_size 25M;

    location / {
        # proxy_pass http://llama_app:80/;
        proxy_pass http://llama_app:80$request_uri;
        # proxy_set_header Host $host:$server_port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    location /assets/ {
        proxy_pass http://llama_app:80/assets/;
        # proxy_set_header Host $host:$server_port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_valid 200 24h;
        add_header Cache-Control "public, max-age=86400";
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://llama_app:80;
        # proxy_set_header Host $host:$server_port;
        proxy_set_header Host $host;
        proxy_cache_valid 200 7d;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
```

#### `./compose.yaml`

```
name: llama-4-researcher

services:
  llama_redis:
    image: redis
    container_name: llama-4-research-redis
    ports:
      - 6379:6379
    restart: always
  llama_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: llama-4-research-app
    secrets:
      - groq_key
      - internal_key
      - linkup_key
      - supabase_api_key
      - supabase_api_url
      - postgres_host
      - postgres_user
      - postgres_db
      - postgres_password
    ports:
      - 8000:80
    depends_on:
      - llama_redis
    restart: always
  llama_register:
    build:
      context: .
      dockerfile: Dockerfile.register
    container_name: llama-4-research-register
    secrets:
      - supabase_api_key
      - supabase_api_url
    ports:
      - 7860:80
    depends_on:
      - llama_redis
    restart: always
  nginx:
    image: nginx:1.27.0-alpine
    container_name: llama-4-research-NGINX
    ports:
      - 80:80
      - 443:443
    depends_on:
      - llama_app
      - llama_register
    restart: always
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/chat.tools.agileimpacts.com:/etc/letsencrypt/live/chat.tools.agileimpacts.com
      - /etc/letsencrypt/archive/chat.tools.agileimpacts.com:/etc/letsencrypt/archive/chat.tools.agileimpacts.com
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/nginx/ssl/dhparam:/etc/nginx/ssl/dhparam

networks:
  default:
    driver: bridge

secrets:
  groq_key:
    environment: groq_api_key
  linkup_key:
    environment: linkup_api_key
  internal_key:
    environment: internal_api_key
  supabase_api_key:
    environment: supa_key
  supabase_api_url:
    environment: supa_url
  postgres_host:
    environment: pgql_host
  postgres_user:
    environment: pgql_user
  postgres_password:
    environment: pgql_psw
  postgres_db:
    environment: pgql_db

volumes:
  pgdata:
```

#### `./deploy/nginx.conf`

```
# Secure default configuration generated by Mozilla SSL Configuration Generator
# generated 2024-01-21, Mozilla Guideline v5.7, nginx 1.24.0, OpenSSL 3.1.4, intermediate configuration
# https://ssl-config.mozilla.org/#server=nginx&version=1.24.0&config=intermediate&openssl=3.1.4&guideline=5.7

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    # To Configure SSL, comment all lines within the Non-SSL section and uncomment all lines under the SSL section. 
    ########################################  Non-SSL  ########################################
    # server_name localhost;
    server_name chat.tools.agileimpacts.com;

    # https://docs.nginx.com/nginx/admin-guide/web-server/compression/
    # gzip on;
    # gzip_vary on;
    # gzip_proxied any;
    # gzip_comp_level 6;
    # gzip_buffers 16 8k;
    # gzip_http_version 1.1;
    # gzip_types text/css application/javascript application/json application/octet-stream;

    # Increase the client_max_body_size to allow larger file uploads
    # The default limits for image uploads as of 11/22/23 is 20MB/file, and 25MB/request
    client_max_body_size 25M;

    #location / {
    #    proxy_pass http://llama_app:80/;
    #}

    ########################################  SSL  ########################################
    # Redirect all http traffic to https
    location / {
        return 301 https://$host:443$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    # https://docs.nginx.com/nginx/admin-guide/web-server/compression/
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/css application/javascript application/json application/octet-stream;

#    ssl_certificate /etc/nginx/ssl/nginx.crt;
#    ssl_certificate_key /etc/nginx/ssl/nginx.key;
    ssl_certificate /etc/letsencrypt/live/chat.tools.agileimpacts.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/chat.tools.agileimpacts.com/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
    ssl_session_tickets off;

    # curl https://ssl-config.mozilla.org/ffdhe2048.txt > /etc/nginx/ssl/dhparam
    ssl_dhparam /etc/nginx/ssl/dhparam;

    # intermediate configuration
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;

    # HSTS (ngx_http_headers_module is required) (63072000 seconds)
    add_header Strict-Transport-Security "max-age=63072000" always;

    # OCSP stapling
    ssl_stapling on;
    ssl_stapling_verify on;

    # verify chain of trust of OCSP response using Root CA and Intermediate certs
    ssl_trusted_certificate /etc/letsencrypt/live/chat.tools.agileimpacts.com/chain.pem;

    # replace with the IP address of your resolver
    resolver 8.8.8.8 8.8.4.4 valid=300s;

    server_name chat.tools.agileimpacts.com;

    # Increase the client_max_body_size to allow larger file uploads
    # The default limits for image uploads as of 11/22/23 is 20MB/file, and 25MB/request
    client_max_body_size 25M;

    location / {
        # proxy_pass http://llama_app:80/;
        proxy_pass http://llama_app:80$request_uri;
        # proxy_set_header Host $host:$server_port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Connection "";
        proxy_read_timeout 600s;
        proxy_send_timeout 600s;
    }

    location /assets/ {
        proxy_pass http://llama_app:80/assets/;
        # proxy_set_header Host $host:$server_port;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_valid 200 24h;
        add_header Cache-Control "public, max-age=86400";
    }

    location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg|woff|woff2|ttf|eot)$ {
        proxy_pass http://llama_app:80;
        # proxy_set_header Host $host:$server_port;
        proxy_set_header Host $host;
        proxy_cache_valid 200 7d;
        proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
```
